### ISSUE TITLE
Links in README are broken

### ISSUE THREAD

**Issue by akuckartz** [sparqlunicorn/unicornQGISdepInstaller#1]
These three URLs in the [README](https://github.com/sparqlunicorn/unicornQGISdepInstaller/blob/master/README.md) link to *different URLs* and therefore result in 404 errors:
https://rdflib.github.io/sparqlwrapper/
https://github.com/RDFLib/rdflib (modified version provided by us)
https://github.com/gweis/isodate

**Comment by situx** [comment]
Thank you! Fixed now.
